dbffs-tools: src/common.c File Reference
common.c File Reference
Common routines.
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include "common.h"
Functions
void die (const char *message)
Print error to stderr and exit with failure status..
Detailed Description
Common routines.
This tool is meant for small file systems used on embedded systems, and keeps everything in memory while building the image.
Copyright 2015 Martin Bo Kristensen Grønholdt <oblivion@ace2>
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file common.c.
Function Documentation
void die (const char * message)
Print error to stderr and exit with failure status..
Exit with failure status.
Parameters
message Message to print with the error.
Definition at line 37 of file common.c.
Referenced by create_dir_entry(), create_entry(), create_file_entry(), create_link_entry(), db_readlink(), main(), populate_fs_image(), write_dir_entry(), write_file_entry(), and write_link_entry().