dbffs-tools: src/dbffs-gen.c File Reference
dbffs-gen.c File Reference
Top level routines to generate a DBF file system image.
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/stat.h>
#include "common.h"
#include "dbffs.h"
#include "dbffs-dir.h"
#include "dbffs-file.h"
#include "dbffs-link.h"
Functions
uint16_t swap16 (uint16_t v)
Convert from host byte order to esp8266 byte order, 16 bit.
uint32_t swap32 (uint32_t v)
Convert from host byte order to esp8266 byte order, 32 bit.
void create_entry (const char *path, char *entryname)
Create a new entry from a path in the root directory.
unsigned int populate_fs_image (const char *root_dir)
Populate data structures for DBFFS from root dir.
Variables
unsigned short fs_n_entries = 0
Number of entries in the file system.
void * fs_entries = NULL
Array of entries in the file system.
void * current_fs_entry = NULL
The current entry in the file system.
Detailed Description
Top level routines to generate a DBF file system image.
Copyright 2015 Martin Bo Kristensen Grønholdt <oblivion@ace2>
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file dbffs-gen.c.
Function Documentation
void create_entry (const char * path, char * entryname)
Create a new entry from a path in the root directory.
Parameters
path Path to the entry in the root directory to use as source.
entryname The name of the entry to add to the file system.
Definition at line 64 of file dbffs-gen.c.
References create_dir_entry(), create_file_entry(), create_link_entry(), current_fs_entry, DBFFS_MAX_ENTRIES, die(), and fs_n_entries.
Referenced by populate_fs_image().
unsigned int populate_fs_image (const char * root_dir)
Populate data structures for DBFFS from root dir.
Parameters
root_dir The directory to start populating from.
Returns
Number of entries add or -1 on error.
Definition at line 103 of file dbffs-gen.c.
References create_entry(), and die().
Referenced by create_dir_entry(), and main().
uint16_t swap16 (uint16_t v)
Convert from host byte order to esp8266 byte order, 16 bit.
Parameters
v Value to convert.
Returns
Swapped value.
Definition at line 42 of file dbffs-gen.c.
Referenced by write_dir_entry().
uint32_t swap32 (uint32_t v)
Convert from host byte order to esp8266 byte order, 32 bit.
Parameters
v Value to convert.
Returns
Swapped value.
Definition at line 52 of file dbffs-gen.c.
Referenced by write_dir_entry(), write_file_entry(), and write_link_entry().