dbffs-tools: src/dbffs-dir.c File Reference
dbffs-dir.c File Reference
Routines for handling directory entries.
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/stat.h>
#include "common.h"
#include "dbffs.h"
#include "dbffs-gen.h"
Functions
struct dbffs_dir_hdr * create_dir_entry (const char *path, char *entryname)
Create a directory entry.
void write_dir_entry (const struct dbffs_dir_hdr *entry, FILE *fp)
Write a dir entry to a file.
Detailed Description
Routines for handling directory entries.
Copyright 2015 Martin Bo Kristensen Grønholdt <oblivion@ace2>
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file dbffs-dir.c.
Function Documentation
struct dbffs_dir_hdr* create_dir_entry (const char * path, char * entryname)
Create a directory entry.
Parameters
path Path to the entry in the root directory to use as source.
entryname The name of the entry to add to the file system.
Returns
A pointer to a directory entry.
Definition at line 36 of file dbffs-dir.c.
References DBFFS_DIR_SIG, die(), and populate_fs_image().
Referenced by create_entry().
void write_dir_entry (const struct dbffs_dir_hdr * entry, FILE * fp)
Write a dir entry to a file.
Parameters
entry Dir entry pointer.
fp Output file pointer.
Definition at line 69 of file dbffs-dir.c.
References die(), swap16(), and swap32().
Referenced by main().