dbffs-tools: src/dbffs-link.c File Reference
dbffs-link.c File Reference
Routines for handlink link entries.
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <unistd.h>
#include "common.h"
#include "dbffs.h"
#include "dbffs-gen.h"
#include "dbffs-file.h"
Functions
static char * db_readlink (const char *path)
Get the contents of a symbolic link.
struct dbffs_link_hdr * create_link_entry (const char *path, char *entryname)
Create a link entry.
void write_link_entry (const struct dbffs_link_hdr *entry, FILE *fp)
Write a link entry to an image.
Detailed Description
Routines for handlink link entries.
Copyright 2015 Martin Bo Kristensen Grønholdt <oblivion@ace2>
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file dbffs-link.c.
Function Documentation
struct dbffs_link_hdr* create_link_entry (const char * path, char * entryname)
Create a link entry.
The offset is not set by this function.
Parameters
path Path to the entry in the root directory to use as source.
entryname The name of the entry to add to the file system.
Returns
A pointert to a link entry.
Definition at line 80 of file dbffs-link.c.
References db_readlink(), DBFFS_LINK_SIG, and die().
Referenced by create_entry().
static char* db_readlink (const char * path) static
Get the contents of a symbolic link.
Parameters
path Path to the link.
Returns
Link target path or NULL.
Definition at line 41 of file dbffs-link.c.
References die().
Referenced by create_link_entry().
void write_link_entry (const struct dbffs_link_hdr * entry, FILE * fp)
Write a link entry to an image.
Parameters
entry Pointer to link entry to write to image.
fp Pointer to an open image file.
Definition at line 106 of file dbffs-link.c.
References die(), and swap32().
Referenced by main().