dbffs-tools: src/dbffs-file.h File Reference
dbffs-file.h File Reference
File related DBFFS routines.
#include "dbffs.h"
Functions
struct dbffs_file_hdr * create_file_entry (const char *path, char *entryname)
Create a file entry.
void write_file_entry (const struct dbffs_file_hdr *entry, FILE *fp)
Write a file entry to a file.
Detailed Description
File related DBFFS routines.
This tool is meant for small file systems used on embedded systems, and keeps everything in memory while building the image.
Copyright 2015 Martin Bo Kristensen Grønholdt <oblivion@ace2>
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file dbffs-file.h.
Function Documentation
struct dbffs_file_hdr* create_file_entry (const char * path, char * entryname)
Create a file entry.
Parameters
path Path to the entry in the root directory to use as source.
entryname The name of the entry to add to the file system.
Returns
Pointer to the directory entry.
Definition at line 37 of file dbffs-file.c.
References DBFFS_FILE_SIG, and die().
Referenced by create_entry().
void write_file_entry (const struct dbffs_file_hdr * entry, FILE * fp)
Write a file entry to a file.
Parameters
entry File entry pointer.
fp Output file pointer.
Definition at line 105 of file dbffs-file.c.
References die(), and swap32().
Referenced by main().